apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: nodejs-api
  name: nodejs-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodejs-api
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-api
    spec:
      containers:
      - image: nodejs-server
        name: nodejs-server1
        imagePullPolicy: Never
        resources: {}
        ports:
          - containerPort: 3001
        env:
          - name: MYID
            value: "INST1"
          - name: PORT
            value: "3001"
        lifecycle:
          preStop:
            exec:
              command: ["sh", "/usr/home/wait-until-unavailable"]
            #httpGet:
            #  path: "hello"
            #  port: 3000
            #  scheme: "HTTP"
      - image: nodejs-server
        name: nodejs-server2
        imagePullPolicy: Never
        resources: {}
        ports:
          - containerPort: 3002
        env:
          - name: MYID
            value: "INST2"
          - name: PORT
            value: "3002"
status: {}
